apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "172.27.129.11"
networking:
  podSubnet: "10.244.0.0/16"
kubernetesVersion: "v1.10.4"
imageRepository: "registry.cn-hangzhou.aliyuncs.com/google_containers"
featureGates:
  CoreDNS: true
