apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jenkins-base
  name: jenkins-base
  namespace: kael-home
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jenkins-base
  template:
    metadata:
      labels:
        k8s-app: jenkins-base
    spec:
      nodeName: kube-node3
      containers:
      - name: jenkins-base
        image: kaelzhan/jenkins:base
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        nfs:
          server: 192.168.2.200
          path: /local/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-base
  namespace: kael-home
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: jenkins-base
    k8s-app: jenkins-base
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http-port
      targetPort: 8080
      nodePort: 32667
    - port: 50000
      name: jnlp-port
      targetPort: 50000
      nodePort: 32668
  selector:
    k8s-app: jenkins-base
